on:
  check_suite:
    types: [completed]

jobs:
  auto_merge_job:
    runs-on: ubuntu-latest
    name: A job to auto approve PRs which past tests for specifc users
    steps:
    - name: Auto Merge Step
      id: AutoMerge
      uses: heyestom/github-js-docker-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        auto-merge-uses: 'heyestom'
        
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: heyestom/github-actions-fun@master  
      with:
        who-to-greet: 'Hello Joe!'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

